language: java
os: linux
dist: trusty
jdk:
  - openjdk8
script: ./gradlew build gitPublishPush  --stacktrace
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
before_install:
  - chmod +x gradlew
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
after_script:
  - git add .
  # something@example.com
  - git config user.email "${GIT_EMAIL}"
  # First Last
  - git config user.name "${GIT_NAME}"
  - git commit -m "updating outputs"
  - git push -f "${GIT_URL}" gh-pages > /dev/null 2>&1